// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTdmkzuEzD9BU1iIksWaI_2ixnJ5fF3RY',
    appId: '1:663185542429:android:7d68dc300704ea2e3565f4',
    messagingSenderId: '663185542429',
    projectId: 'proxima-ride-app',
    storageBucket: 'proxima-ride-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKoh-bTPRD6q2LevMMUH3hCvnfjXJEu4',
    appId: '1:663185542429:ios:f4e203e109dd936c3565f4',
    messagingSenderId: '663185542429',
    projectId: 'proxima-ride-app',
    storageBucket: 'proxima-ride-app.appspot.com',
    iosBundleId: 'com.example.proximaRide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZT7ai59WwGow0PZWm_SpRd3oVqWfsg1Y',
    appId: '1:663185542429:web:83293e957423573c3565f4',
    messagingSenderId: '663185542429',
    projectId: 'proxima-ride-app',
    authDomain: 'proxima-ride-app.firebaseapp.com',
    storageBucket: 'proxima-ride-app.appspot.com',
    measurementId: 'G-33E79Y4BN5',
  );

}